In [2]:
import pandas as pd

orders = pd.read_csv("../data/orders.csv")
products = pd.read_csv("../data/products.csv")

In [4]:
import os

os.getcwd()

'/Users/tamerabdelrasoul/Desktop/cds492/code'

In [6]:
os.listdir("../data")

['products.csv',
 'orders.csv',
 '.DS_Store',
 'basket.csv',
 'order_products__train.csv',
 'departments.csv',
 'Groceries data.csv',
 'aisles.csv',
 'order_products__prior.csv']

In [8]:
import pandas as pd
import numpy as np

In [10]:
# we start first with the instacart tables only
# then we read the data our data files and assign them to variables

orders = pd.read_csv("../data/orders.csv")
order_prior = pd.read_csv("../data/order_products__prior.csv")
products = pd.read_csv("../data/products.csv")
aisles = pd.read_csv("../data/aisles.csv")
departments = pd.read_csv("../data/departments.csv")

In [12]:
print("Orders shape:", orders.shape)
print("Order Prior shape:", order_prior.shape)
print("Products shape:", products.shape)

orders.head()

Orders shape: (3421083, 7)
Order Prior shape: (32434489, 4)
Products shape: (49688, 4)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [14]:
# we check missing values for orders,oder_prior, and products datasets
# days_since_prior_order has a large values which means those are the customers who necer ordered before so it is 
# logicall to have this column filld with a null value "NaN"
orders.isnull().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

In [16]:
order_prior.isnull().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [18]:
products.isnull().sum()

product_id       0
product_name     0
aisle_id         0
department_id    0
dtype: int64

In [20]:
# removing duplicate values
orders = orders.drop_duplicates()
order_prior = order_prior.drop_duplicates()
products = products.drop_duplicates()

In [22]:
# standarize product names
#convert to lower case
#remove extra spaces at the begining and end of text
products["product_name"] = products["product_name"].str.lower().str.strip()

In [24]:
# we can check for unique values
# how many unique products are in the dataset
products["product_name"].nunique()

49588

In [26]:
# part 2
# we need to know what we are working with
# understand the datasets

print("Orders:", orders.shape)
print("Order-Product (Prior):", order_prior.shape)
print("Products:", products.shape)
print("Aisles:", aisles.shape)
print("Departments:", departments.shape)

Orders: (3421083, 7)
Order-Product (Prior): (32434489, 4)
Products: (49688, 4)
Aisles: (134, 2)
Departments: (21, 2)

In [28]:
orders["order_id"].nunique()

3421083

In [30]:
products["product_id"].nunique()

49688

In [32]:
# we can get a percentage of repeated orders this can help us with our business question too
# note: this column "reordered" has 1s and 0s. 1 means did order again 0 means did not
order_prior["reordered"].mean()

0.5896974667922161

In [34]:
order_prior_products = order_prior.merge(
    products,
    on="product_id",
    how="left"
)

order_prior_products.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id
0,2,33120,1,1,organic egg whites,86,16
1,2,28985,2,1,michigan organic kale,83,4
2,2,9327,3,0,garlic powder,104,13
3,2,45918,4,1,coconut butter,19,13
4,2,30035,5,0,natural sweetener,17,13